# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Recipe to demonstrate FusedLibraryPlugin usage.
  """

[agpVersion]
min = "8.9.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":fusedLibrary:assemble",
    ":fusedLibrary:report",
    ":fusedLibrary:generatePomFileForMavenPublication",
    ":fusedLibrary:publishReleasePublicationToMyrepoRepository",
    ":fusedLibrary:publishReleasePublicationToMyrepoRepository",
    ":app:testDebugUnitTest",
    ":app:connectedDebugAndroidTest"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = []

